### ISSUE TITLE
Add Example to README

### ISSUE THREAD

**Issue by weitzman** [amcgowanca/discoverable_entity_bundle_classes#2]
This package could really benefit from some examples. `discoverable_entity_bundle_classes` is a fine name but at first read its so generic that its hard to grasp. Examples might be lifted from https://www.drupal.org/project/drupal/issues/2570593

**Comment by weitzman** [comment]
In addition to showing an example use case, it would be great to show how to setup/configure for that use case. Its fine to link to docs that live in Doxygen if you want strict DRY.

**Comment by amcgowanca** [comment]
@weitzman , I've updated the README.md as part of 1.0.2 release. Let me know if additional clarity or information should be provided; I tried to highlight:

1. Usage instructions
2. An example (near bottom)
